"""Core safe-slice detector library.

This package intentionally exposes only the detector algorithm and the
minimal data/protocol types needed to run it.
"""

from .ambiguity import (
    ambiguity_bounds,
    exact_identification_rounds,
    fano_lower_bound_rounds,
    normalize_prior,
    restricted_success_upper_bound,
    single_shot_upper_bound,
    succ_questions_unrestricted,
)
from .claim_graph_adapter import (
    chain_from_claim_graph,
    ClaimGraphAdapterConfig,
    task_from_claim_graph,
)
from .interfaces import Checker, PromptRenderer, QuestionFamily, Sampler
from .models import (
    AmbiguityReport,
    AmbiguityRoutingInterpretation,
    AmbiguityRoutingStatus,
    AmbiguitySpec,
    AnalysisParameters,
    BoundaryMode,
    BoundMethod,
    BoundaryEstimate,
    ChainLocalPartition,
    ChainReport,
    ChainSpec,
    CheckerResult,
    DetectorReport,
    DetectorStateSummary,
    GlobalObstruction,
    GlobalObstructionKind,
    LocalUnsafeReason,
    SamplingMode,
    RestrictedQuestionFamilyReport,
    RestrictedQuestionFamilyStatus,
    RouteLabel,
    SampleTrace,
    SliceEstimate,
    SliceSpec,
    TaskPartition,
    TaskSpec,
    ThresholdSpec,
    WitnessPair,
)
from .pipeline import SafeSliceDetector
from .policy import (
    boundary_estimates_from_slices,
    chain_effective_route,
    classify_chain,
    detector_state_summary,
    empirical_medim_lower_bound,
    effective_success_hats,
    global_obstructions,
    isotonic_nonincreasing,
    summarize_task_partition,
    witness_pairs_from_boundaries,
)
from .stats import (
    agresti_coull_interval,
    beta_quantile,
    clopper_pearson_interval,
    drop_bounds,
    empirical_bernstein_radius,
    enough_precision,
    event_delta,
    hoeffding_radius,
    jeffreys_interval,
    regularized_beta,
    slice_bounds,
    SUPPORTED_BOUND_METHODS,
    wilson_interval,
)

__all__ = [
    "AmbiguityReport",
    "AmbiguityRoutingInterpretation",
    "AmbiguityRoutingStatus",
    "AmbiguitySpec",
    "AnalysisParameters",
    "BoundaryMode",
    "BoundMethod",
    "BoundaryEstimate",
    "ChainLocalPartition",
    "ChainReport",
    "ChainSpec",
    "Checker",
    "CheckerResult",
    "ClaimGraphAdapterConfig",
    "DetectorReport",
    "DetectorStateSummary",
    "GlobalObstruction",
    "GlobalObstructionKind",
    "LocalUnsafeReason",
    "PromptRenderer",
    "QuestionFamily",
    "RestrictedQuestionFamilyReport",
    "RestrictedQuestionFamilyStatus",
    "RouteLabel",
    "SafeSliceDetector",
    "SampleTrace",
    "Sampler",
    "SamplingMode",
    "SliceEstimate",
    "SliceSpec",
    "TaskPartition",
    "TaskSpec",
    "ThresholdSpec",
    "WitnessPair",
    "ambiguity_bounds",
    "agresti_coull_interval",
    "beta_quantile",
    "boundary_estimates_from_slices",
    "chain_from_claim_graph",
    "chain_effective_route",
    "classify_chain",
    "clopper_pearson_interval",
    "detector_state_summary",
    "drop_bounds",
    "empirical_medim_lower_bound",
    "empirical_bernstein_radius",
    "enough_precision",
    "event_delta",
    "exact_identification_rounds",
    "fano_lower_bound_rounds",
    "global_obstructions",
    "hoeffding_radius",
    "isotonic_nonincreasing",
    "jeffreys_interval",
    "normalize_prior",
    "regularized_beta",
    "restricted_success_upper_bound",
    "single_shot_upper_bound",
    "slice_bounds",
    "succ_questions_unrestricted",
    "summarize_task_partition",
    "SUPPORTED_BOUND_METHODS",
    "task_from_claim_graph",
    "wilson_interval",
    "witness_pairs_from_boundaries",
    "effective_success_hats",
]
